// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"helloworld/internal/biz"
	"helloworld/internal/conf"
	"helloworld/internal/data"
	"helloworld/internal/server"
	"helloworld/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
//
//	func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
//		dataData, cleanup, err := data.NewData(confData, logger)
//		if err != nil {
//			return nil, nil, err
//		}
//		greeterRepo := data.NewGreeterRepo(dataData, logger)
//		greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
//		greeterService := service.NewGreeterService(greeterUsecase)
//		grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
//		httpServer := server.NewHTTPServer(confServer, greeterService, logger)
//		app := newApp(logger, grpcServer, httpServer)
//		return app, func() {
//			cleanup()
//		}, nil
//	}
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewMysql(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup2, err := data.NewRedis(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData, cleanup3, err := data.NewData(confData, logger, db, client)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
