server:
  http:
    addr: 127.0.0.1:8080
    timeout: 1s
  grpc:
    addr: 127.0.0.1:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:cd423a2933d92b70@tcp(14.103.168.20:3306)/order?parseTime=True&loc=Local
  redis:
    addr: 14.103.168.20:6379
    password: cd423a2933d92b70
    read_timeout: 0.2s
    write_timeout: 0.2s
