// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SendSmsCode   string                 `protobuf:"bytes,2,opt,name=SendSmsCode,proto3" json:"SendSmsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendSmsRequest) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

type SendSmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReply) Reset() {
	*x = SendSmsReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReply) ProtoMessage() {}

func (x *SendSmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReply.ProtoReflect.Descriptor instead.
func (*SendSmsReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendSmsReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SendSmsCode   string                 `protobuf:"bytes,2,opt,name=SendSmsCode,proto3" json:"SendSmsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginRequest) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex           string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UpdateUserRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UpdateUserRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type UpdateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReply) Reset() {
	*x = UpdateUserReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReply) ProtoMessage() {}

func (x *UpdateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReply.ProtoReflect.Descriptor instead.
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InfoUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoUserRequest) Reset() {
	*x = InfoUserRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoUserRequest) ProtoMessage() {}

func (x *InfoUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoUserRequest.ProtoReflect.Descriptor instead.
func (*InfoUserRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *InfoUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InfoUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Info          []*Data                `protobuf:"bytes,3,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoUserReply) Reset() {
	*x = InfoUserReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoUserReply) ProtoMessage() {}

func (x *InfoUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoUserReply.ProtoReflect.Descriptor instead.
func (*InfoUserReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{7}
}

func (x *InfoUserReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InfoUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InfoUserReply) GetInfo() []*Data {
	if x != nil {
		return x.Info
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Sex           string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{8}
}

func (x *Data) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Data) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Data) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *Data) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

type RealNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCard        string                 `protobuf:"bytes,3,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameRequest) Reset() {
	*x = RealNameRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameRequest) ProtoMessage() {}

func (x *RealNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameRequest.ProtoReflect.Descriptor instead.
func (*RealNameRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{9}
}

func (x *RealNameRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RealNameRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *RealNameRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

type RealNameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameReply) Reset() {
	*x = RealNameReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameReply) ProtoMessage() {}

func (x *RealNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameReply.ProtoReflect.Descriptor instead.
func (*RealNameReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{10}
}

func (x *RealNameReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RealNameReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverRegisterRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NickName             string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	CarAge               int32                  `protobuf:"varint,4,opt,name=car_age,json=carAge,proto3" json:"car_age,omitempty"`
	Mobile               string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	FileId               int32                  `protobuf:"varint,6,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	IdCardFileId         string                 `protobuf:"bytes,7,opt,name=id_card_file_id,json=idCardFileId,proto3" json:"id_card_file_id,omitempty"`
	DriverLicenseFileId  string                 `protobuf:"bytes,8,opt,name=driver_license_file_id,json=driverLicenseFileId,proto3" json:"driver_license_file_id,omitempty"`
	DrivingLicenseFileId string                 `protobuf:"bytes,9,opt,name=driving_license_file_id,json=drivingLicenseFileId,proto3" json:"driving_license_file_id,omitempty"`
	AvatorFileId         string                 `protobuf:"bytes,10,opt,name=avator_file_id,json=avatorFileId,proto3" json:"avator_file_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DriverRegisterRequest) Reset() {
	*x = DriverRegisterRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegisterRequest) ProtoMessage() {}

func (x *DriverRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegisterRequest.ProtoReflect.Descriptor instead.
func (*DriverRegisterRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{11}
}

func (x *DriverRegisterRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DriverRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverRegisterRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *DriverRegisterRequest) GetCarAge() int32 {
	if x != nil {
		return x.CarAge
	}
	return 0
}

func (x *DriverRegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *DriverRegisterRequest) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *DriverRegisterRequest) GetIdCardFileId() string {
	if x != nil {
		return x.IdCardFileId
	}
	return ""
}

func (x *DriverRegisterRequest) GetDriverLicenseFileId() string {
	if x != nil {
		return x.DriverLicenseFileId
	}
	return ""
}

func (x *DriverRegisterRequest) GetDrivingLicenseFileId() string {
	if x != nil {
		return x.DrivingLicenseFileId
	}
	return ""
}

func (x *DriverRegisterRequest) GetAvatorFileId() string {
	if x != nil {
		return x.AvatorFileId
	}
	return ""
}

type DriverRegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegisterReply) Reset() {
	*x = DriverRegisterReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegisterReply) ProtoMessage() {}

func (x *DriverRegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegisterReply.ProtoReflect.Descriptor instead.
func (*DriverRegisterReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{12}
}

func (x *DriverRegisterReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverRegisterReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverStatusRequest) Reset() {
	*x = DriverStatusRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverStatusRequest) ProtoMessage() {}

func (x *DriverStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverStatusRequest.ProtoReflect.Descriptor instead.
func (*DriverStatusRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{13}
}

func (x *DriverStatusRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DriverStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverStatusReply) Reset() {
	*x = DriverStatusReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverStatusReply) ProtoMessage() {}

func (x *DriverStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverStatusReply.ProtoReflect.Descriptor instead.
func (*DriverStatusReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{14}
}

func (x *DriverStatusReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverStatusReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DriverUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	CarAge        int32                  `protobuf:"varint,4,opt,name=car_age,json=carAge,proto3" json:"car_age,omitempty"`
	Mobile        string                 `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverUpdateRequest) Reset() {
	*x = DriverUpdateRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverUpdateRequest) ProtoMessage() {}

func (x *DriverUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverUpdateRequest.ProtoReflect.Descriptor instead.
func (*DriverUpdateRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{15}
}

func (x *DriverUpdateRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverUpdateRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *DriverUpdateRequest) GetCarAge() int32 {
	if x != nil {
		return x.CarAge
	}
	return 0
}

func (x *DriverUpdateRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type DriverUpdateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverUpdateReply) Reset() {
	*x = DriverUpdateReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverUpdateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverUpdateReply) ProtoMessage() {}

func (x *DriverUpdateReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverUpdateReply.ProtoReflect.Descriptor instead.
func (*DriverUpdateReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{16}
}

func (x *DriverUpdateReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverUpdateReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddressListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListRequest) Reset() {
	*x = AddressListRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListRequest) ProtoMessage() {}

func (x *AddressListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListRequest.ProtoReflect.Descriptor instead.
func (*AddressListRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{17}
}

func (x *AddressListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AddressListRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AddressListRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressListRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressListRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

type AddressListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AddressList         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressListReply) Reset() {
	*x = AddressListReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressListReply) ProtoMessage() {}

func (x *AddressListReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressListReply.ProtoReflect.Descriptor instead.
func (*AddressListReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{18}
}

func (x *AddressListReply) GetList() []*AddressList {
	if x != nil {
		return x.List
	}
	return nil
}

type AddressList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Province      string                 `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"`
	Tel           string                 `protobuf:"bytes,5,opt,name=tel,proto3" json:"tel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressList) Reset() {
	*x = AddressList{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressList) ProtoMessage() {}

func (x *AddressList) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressList.ProtoReflect.Descriptor instead.
func (*AddressList) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{19}
}

func (x *AddressList) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressList) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressList) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressList) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *AddressList) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

type UserAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddressRequest) Reset() {
	*x = UserAddressRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddressRequest) ProtoMessage() {}

func (x *UserAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddressRequest.ProtoReflect.Descriptor instead.
func (*UserAddressRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{20}
}

func (x *UserAddressRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserAddressRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UserAddressRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type UserAddressReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Province      string                 `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddressReply) Reset() {
	*x = UserAddressReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddressReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddressReply) ProtoMessage() {}

func (x *UserAddressReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddressReply.ProtoReflect.Descriptor instead.
func (*UserAddressReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{21}
}

func (x *UserAddressReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserAddressReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserAddressReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserAddressReply) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserAddressReply) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserAddressReply) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartLng      float64                `protobuf:"fixed64,2,opt,name=start_lng,json=startLng,proto3" json:"start_lng,omitempty"`
	StartLat      float64                `protobuf:"fixed64,3,opt,name=start_lat,json=startLat,proto3" json:"start_lat,omitempty"`
	EndLng        float64                `protobuf:"fixed64,4,opt,name=end_lng,json=endLng,proto3" json:"end_lng,omitempty"`
	EndLat        float64                `protobuf:"fixed64,5,opt,name=end_lat,json=endLat,proto3" json:"end_lat,omitempty"`
	StartAddr     string                 `protobuf:"bytes,6,opt,name=start_addr,json=startAddr,proto3" json:"start_addr,omitempty"`
	EndAddr       string                 `protobuf:"bytes,7,opt,name=end_addr,json=endAddr,proto3" json:"end_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTripRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTripRequest) GetStartLng() float64 {
	if x != nil {
		return x.StartLng
	}
	return 0
}

func (x *CreateTripRequest) GetStartLat() float64 {
	if x != nil {
		return x.StartLat
	}
	return 0
}

func (x *CreateTripRequest) GetEndLng() float64 {
	if x != nil {
		return x.EndLng
	}
	return 0
}

func (x *CreateTripRequest) GetEndLat() float64 {
	if x != nil {
		return x.EndLat
	}
	return 0
}

func (x *CreateTripRequest) GetStartAddr() string {
	if x != nil {
		return x.StartAddr
	}
	return ""
}

func (x *CreateTripRequest) GetEndAddr() string {
	if x != nil {
		return x.EndAddr
	}
	return ""
}

type CreateTripReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        int64                  `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	OrderCode     string                 `protobuf:"bytes,2,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	OrderStatus   string                 `protobuf:"bytes,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripReply) Reset() {
	*x = CreateTripReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripReply) ProtoMessage() {}

func (x *CreateTripReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripReply.ProtoReflect.Descriptor instead.
func (*CreateTripReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{23}
}

func (x *CreateTripReply) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *CreateTripReply) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *CreateTripReply) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTripReply) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

type DriverOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int32                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OrderCode     string                 `protobuf:"bytes,2,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOrderRequest) Reset() {
	*x = DriverOrderRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOrderRequest) ProtoMessage() {}

func (x *DriverOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverOrderRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{24}
}

func (x *DriverOrderRequest) GetDriverId() int32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverOrderRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

type DriverOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOrderReply) Reset() {
	*x = DriverOrderReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOrderReply) ProtoMessage() {}

func (x *DriverOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOrderReply.ProtoReflect.Descriptor instead.
func (*DriverOrderReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{25}
}

func (x *DriverOrderReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverOrderReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PayOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderRequest) Reset() {
	*x = PayOrderRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderRequest) ProtoMessage() {}

func (x *PayOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderRequest.ProtoReflect.Descriptor instead.
func (*PayOrderRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{26}
}

func (x *PayOrderRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PayOrderReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	PayUrl        string                 `protobuf:"bytes,3,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderReply) Reset() {
	*x = PayOrderReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReply) ProtoMessage() {}

func (x *PayOrderReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReply.ProtoReflect.Descriptor instead.
func (*PayOrderReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{27}
}

func (x *PayOrderReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PayOrderReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PayOrderReply) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

var File_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"J\n" +
	"\x0eSendSmsRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12 \n" +
	"\vSendSmsCode\x18\x02 \x01(\tR\vSendSmsCode\"<\n" +
	"\fSendSmsReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\fLoginRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12 \n" +
	"\vSendSmsCode\x18\x02 \x01(\tR\vSendSmsCode\"P\n" +
	"\n" +
	"LoginReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"i\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bnickName\x18\x03 \x01(\tR\bnickName\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\"?\n" +
	"\x0fUpdateUserReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\x0fInfoUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"f\n" +
	"\rInfoUserReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04info\x18\x03 \x03(\v2\x13.helloworld.v1.DataR\x04info\"h\n" +
	"\x04Data\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x1a\n" +
	"\bnickName\x18\x03 \x01(\tR\bnickName\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\"`\n" +
	"\x0fRealNameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x17\n" +
	"\aid_card\x18\x03 \x01(\tR\x06idCard\"=\n" +
	"\rRealNameReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe4\x02\n" +
	"\x15DriverRegisterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x17\n" +
	"\acar_age\x18\x04 \x01(\x05R\x06carAge\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\x12\x17\n" +
	"\afile_id\x18\x06 \x01(\x05R\x06fileId\x12%\n" +
	"\x0fid_card_file_id\x18\a \x01(\tR\fidCardFileId\x123\n" +
	"\x16driver_license_file_id\x18\b \x01(\tR\x13driverLicenseFileId\x125\n" +
	"\x17driving_license_file_id\x18\t \x01(\tR\x14drivingLicenseFileId\x12$\n" +
	"\x0eavator_file_id\x18\n" +
	" \x01(\tR\favatorFileId\"C\n" +
	"\x13DriverRegisterReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x13DriverStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"A\n" +
	"\x11DriverStatusReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x87\x01\n" +
	"\x13DriverUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x17\n" +
	"\acar_age\x18\x04 \x01(\x05R\x06carAge\x12\x16\n" +
	"\x06mobile\x18\x05 \x01(\tR\x06mobile\"A\n" +
	"\x11DriverUpdateReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x88\x01\n" +
	"\x12AddressListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x05 \x01(\tR\bdistrict\"B\n" +
	"\x10AddressListReply\x12.\n" +
	"\x04list\x18\x01 \x03(\v2\x1a.helloworld.v1.AddressListR\x04list\"\x85\x01\n" +
	"\vAddressList\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\x02 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x04 \x01(\tR\bdistrict\x12\x10\n" +
	"\x03tel\x18\x05 \x01(\tR\x03tel\"g\n" +
	"\x12UserAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\"\xa6\x01\n" +
	"\x10UserAddressReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\bprovince\x18\x04 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x06 \x01(\tR\bdistrict\"\xd2\x01\n" +
	"\x11CreateTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tstart_lng\x18\x02 \x01(\x01R\bstartLng\x12\x1b\n" +
	"\tstart_lat\x18\x03 \x01(\x01R\bstartLat\x12\x17\n" +
	"\aend_lng\x18\x04 \x01(\x01R\x06endLng\x12\x17\n" +
	"\aend_lat\x18\x05 \x01(\x01R\x06endLat\x12\x1d\n" +
	"\n" +
	"start_addr\x18\x06 \x01(\tR\tstartAddr\x12\x19\n" +
	"\bend_addr\x18\a \x01(\tR\aendAddr\"\x82\x01\n" +
	"\x0fCreateTripReply\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\x03R\x06tripId\x12\x1d\n" +
	"\n" +
	"order_code\x18\x02 \x01(\tR\torderCode\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12!\n" +
	"\forder_status\x18\x04 \x01(\tR\vorderStatus\"P\n" +
	"\x12DriverOrderRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x05R\bdriverId\x12\x1d\n" +
	"\n" +
	"order_code\x18\x02 \x01(\tR\torderCode\"@\n" +
	"\x10DriverOrderReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\x0fPayOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"N\n" +
	"\rPayOrderReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\apay_url\x18\x03 \x01(\tR\x06payUrl2\x88\v\n" +
	"\aGreeter\x12_\n" +
	"\aSendSms\x12\x1d.helloworld.v1.SendSmsRequest\x1a\x1b.helloworld.v1.SendSmsReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/user/sendSms\x12W\n" +
	"\x05Login\x12\x1b.helloworld.v1.LoginRequest\x1a\x19.helloworld.v1.LoginReply\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/user/login\x12k\n" +
	"\n" +
	"UpdateUser\x12 .helloworld.v1.UpdateUserRequest\x1a\x1e.helloworld.v1.UpdateUserReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/user/updateUser\x12c\n" +
	"\bInfoUser\x12\x1e.helloworld.v1.InfoUserRequest\x1a\x1c.helloworld.v1.InfoUserReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/infoUser\x12`\n" +
	"\bRealName\x12\x1e.helloworld.v1.RealNameRequest\x1a\x1c.helloworld.v1.RealNameReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/user/realName\x12}\n" +
	"\x0eDriverRegister\x12$.helloworld.v1.DriverRegisterRequest\x1a\".helloworld.v1.DriverRegisterReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/driver/driverRegister\x12u\n" +
	"\fDriverStatus\x12\".helloworld.v1.DriverStatusRequest\x1a .helloworld.v1.DriverStatusReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/driver/driverStatus\x12u\n" +
	"\fDriverUpdate\x12\".helloworld.v1.DriverUpdateRequest\x1a .helloworld.v1.DriverUpdateReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/driver/driverUpdate\x12n\n" +
	"\vAddressList\x12!.helloworld.v1.AddressListRequest\x1a\x1f.helloworld.v1.AddressListReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/map/addressList\x12n\n" +
	"\vUserAddress\x12!.helloworld.v1.UserAddressRequest\x1a\x1f.helloworld.v1.UserAddressReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/map/userAddress\x12j\n" +
	"\n" +
	"CreateTrip\x12 .helloworld.v1.CreateTripRequest\x1a\x1e.helloworld.v1.CreateTripReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/map/createTrip\x12q\n" +
	"\vDriverOrder\x12!.helloworld.v1.DriverOrderRequest\x1a\x1f.helloworld.v1.DriverOrderReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/driver/DriverOrder\x12c\n" +
	"\bPayOrder\x12\x1e.helloworld.v1.PayOrderRequest\x1a\x1c.helloworld.v1.PayOrderReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/payOrderBT\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z\x1fhelloworld/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_helloworld_v1_greeter_proto_rawDescData
}

var file_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_helloworld_v1_greeter_proto_goTypes = []any{
	(*SendSmsRequest)(nil),        // 0: helloworld.v1.SendSmsRequest
	(*SendSmsReply)(nil),          // 1: helloworld.v1.SendSmsReply
	(*LoginRequest)(nil),          // 2: helloworld.v1.LoginRequest
	(*LoginReply)(nil),            // 3: helloworld.v1.LoginReply
	(*UpdateUserRequest)(nil),     // 4: helloworld.v1.UpdateUserRequest
	(*UpdateUserReply)(nil),       // 5: helloworld.v1.UpdateUserReply
	(*InfoUserRequest)(nil),       // 6: helloworld.v1.InfoUserRequest
	(*InfoUserReply)(nil),         // 7: helloworld.v1.InfoUserReply
	(*Data)(nil),                  // 8: helloworld.v1.Data
	(*RealNameRequest)(nil),       // 9: helloworld.v1.RealNameRequest
	(*RealNameReply)(nil),         // 10: helloworld.v1.RealNameReply
	(*DriverRegisterRequest)(nil), // 11: helloworld.v1.DriverRegisterRequest
	(*DriverRegisterReply)(nil),   // 12: helloworld.v1.DriverRegisterReply
	(*DriverStatusRequest)(nil),   // 13: helloworld.v1.DriverStatusRequest
	(*DriverStatusReply)(nil),     // 14: helloworld.v1.DriverStatusReply
	(*DriverUpdateRequest)(nil),   // 15: helloworld.v1.DriverUpdateRequest
	(*DriverUpdateReply)(nil),     // 16: helloworld.v1.DriverUpdateReply
	(*AddressListRequest)(nil),    // 17: helloworld.v1.AddressListRequest
	(*AddressListReply)(nil),      // 18: helloworld.v1.AddressListReply
	(*AddressList)(nil),           // 19: helloworld.v1.AddressList
	(*UserAddressRequest)(nil),    // 20: helloworld.v1.UserAddressRequest
	(*UserAddressReply)(nil),      // 21: helloworld.v1.UserAddressReply
	(*CreateTripRequest)(nil),     // 22: helloworld.v1.CreateTripRequest
	(*CreateTripReply)(nil),       // 23: helloworld.v1.CreateTripReply
	(*DriverOrderRequest)(nil),    // 24: helloworld.v1.DriverOrderRequest
	(*DriverOrderReply)(nil),      // 25: helloworld.v1.DriverOrderReply
	(*PayOrderRequest)(nil),       // 26: helloworld.v1.PayOrderRequest
	(*PayOrderReply)(nil),         // 27: helloworld.v1.PayOrderReply
}
var file_helloworld_v1_greeter_proto_depIdxs = []int32{
	8,  // 0: helloworld.v1.InfoUserReply.info:type_name -> helloworld.v1.Data
	19, // 1: helloworld.v1.AddressListReply.list:type_name -> helloworld.v1.AddressList
	0,  // 2: helloworld.v1.Greeter.SendSms:input_type -> helloworld.v1.SendSmsRequest
	2,  // 3: helloworld.v1.Greeter.Login:input_type -> helloworld.v1.LoginRequest
	4,  // 4: helloworld.v1.Greeter.UpdateUser:input_type -> helloworld.v1.UpdateUserRequest
	6,  // 5: helloworld.v1.Greeter.InfoUser:input_type -> helloworld.v1.InfoUserRequest
	9,  // 6: helloworld.v1.Greeter.RealName:input_type -> helloworld.v1.RealNameRequest
	11, // 7: helloworld.v1.Greeter.DriverRegister:input_type -> helloworld.v1.DriverRegisterRequest
	13, // 8: helloworld.v1.Greeter.DriverStatus:input_type -> helloworld.v1.DriverStatusRequest
	15, // 9: helloworld.v1.Greeter.DriverUpdate:input_type -> helloworld.v1.DriverUpdateRequest
	17, // 10: helloworld.v1.Greeter.AddressList:input_type -> helloworld.v1.AddressListRequest
	20, // 11: helloworld.v1.Greeter.UserAddress:input_type -> helloworld.v1.UserAddressRequest
	22, // 12: helloworld.v1.Greeter.CreateTrip:input_type -> helloworld.v1.CreateTripRequest
	24, // 13: helloworld.v1.Greeter.DriverOrder:input_type -> helloworld.v1.DriverOrderRequest
	26, // 14: helloworld.v1.Greeter.PayOrder:input_type -> helloworld.v1.PayOrderRequest
	1,  // 15: helloworld.v1.Greeter.SendSms:output_type -> helloworld.v1.SendSmsReply
	3,  // 16: helloworld.v1.Greeter.Login:output_type -> helloworld.v1.LoginReply
	5,  // 17: helloworld.v1.Greeter.UpdateUser:output_type -> helloworld.v1.UpdateUserReply
	7,  // 18: helloworld.v1.Greeter.InfoUser:output_type -> helloworld.v1.InfoUserReply
	10, // 19: helloworld.v1.Greeter.RealName:output_type -> helloworld.v1.RealNameReply
	12, // 20: helloworld.v1.Greeter.DriverRegister:output_type -> helloworld.v1.DriverRegisterReply
	14, // 21: helloworld.v1.Greeter.DriverStatus:output_type -> helloworld.v1.DriverStatusReply
	16, // 22: helloworld.v1.Greeter.DriverUpdate:output_type -> helloworld.v1.DriverUpdateReply
	18, // 23: helloworld.v1.Greeter.AddressList:output_type -> helloworld.v1.AddressListReply
	21, // 24: helloworld.v1.Greeter.UserAddress:output_type -> helloworld.v1.UserAddressReply
	23, // 25: helloworld.v1.Greeter.CreateTrip:output_type -> helloworld.v1.CreateTripReply
	25, // 26: helloworld.v1.Greeter.DriverOrder:output_type -> helloworld.v1.DriverOrderReply
	27, // 27: helloworld.v1.Greeter.PayOrder:output_type -> helloworld.v1.PayOrderReply
	15, // [15:28] is the sub-list for method output_type
	2,  // [2:15] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_helloworld_v1_greeter_proto_init() }
func file_helloworld_v1_greeter_proto_init() {
	if File_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_helloworld_v1_greeter_proto = out.File
	file_helloworld_v1_greeter_proto_goTypes = nil
	file_helloworld_v1_greeter_proto_depIdxs = nil
}
