//syntax = "proto3";
//
//package helloworld.v1;
//
//import "google/api/annotations.proto";
//
//option go_package = "helloworld/api/helloworld/v1;v1";
//option java_multiple_files = true;
//option java_package = "dev.kratos.api.helloworld.v1";
//option java_outer_classname = "HelloworldProtoV1";
//
//// The greeting service definition.
//service Greeter {
//  // Sends a greeting
//
//  rpc RegisterUser (RegisterRequest) returns (RegisterReply) {
//    option (google.api.http) = {
//      post: "/user/register"
//      body: "*"
//    };
//  }
//
//}
//
//// The request message containing the user's name.
//message RegisterRequest {
//  string username = 1;
//  string password = 2;
//}
//
//// The response message containing the greetings
//message RegisterReply {
//  int64 id = 1;
//}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: helloworld/v1/greeter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送验证码
type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SendSmsCode   string                 `protobuf:"bytes,2,opt,name=SendSmsCode,proto3" json:"SendSmsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *SendSmsRequest) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

// 用户注册响应
type SendSmsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsReply) Reset() {
	*x = SendSmsReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsReply) ProtoMessage() {}

func (x *SendSmsReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsReply.ProtoReflect.Descriptor instead.
func (*SendSmsReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendSmsReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 注册登录
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SendSmsCode   string                 `protobuf:"bytes,2,opt,name=SendSmsCode,proto3" json:"SendSmsCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterRequest) GetSendSmsCode() string {
	if x != nil {
		return x.SendSmsCode
	}
	return ""
}

// 用户注册响应
type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegisterReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"J\n" +
	"\x0eSendSmsRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12 \n" +
	"\vSendSmsCode\x18\x02 \x01(\tR\vSendSmsCode\"4\n" +
	"\fSendSmsReply\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\"K\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12 \n" +
	"\vSendSmsCode\x18\x02 \x01(\tR\vSendSmsCode\"K\n" +
	"\rRegisterReply\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\x12\x14\n" +
	"\x05Token\x18\x03 \x01(\tR\x05Token2\xcf\x01\n" +
	"\aGreeter\x12_\n" +
	"\aSendSms\x12\x1d.helloworld.v1.SendSmsRequest\x1a\x1b.helloworld.v1.SendSmsReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/user/sensSms\x12c\n" +
	"\bRegister\x12\x1e.helloworld.v1.RegisterRequest\x1a\x1c.helloworld.v1.RegisterReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/user/registerBT\n" +
	"\x1cdev.kratos.api.helloworld.v1B\x11HelloworldProtoV1P\x01Z\x1fhelloworld/api/helloworld/v1;v1b\x06proto3"

var (
	file_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_helloworld_v1_greeter_proto_rawDescData
}

var file_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_helloworld_v1_greeter_proto_goTypes = []any{
	(*SendSmsRequest)(nil),  // 0: helloworld.v1.SendSmsRequest
	(*SendSmsReply)(nil),    // 1: helloworld.v1.SendSmsReply
	(*RegisterRequest)(nil), // 2: helloworld.v1.RegisterRequest
	(*RegisterReply)(nil),   // 3: helloworld.v1.RegisterReply
}
var file_helloworld_v1_greeter_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.Greeter.SendSms:input_type -> helloworld.v1.SendSmsRequest
	2, // 1: helloworld.v1.Greeter.Register:input_type -> helloworld.v1.RegisterRequest
	1, // 2: helloworld.v1.Greeter.SendSms:output_type -> helloworld.v1.SendSmsReply
	3, // 3: helloworld.v1.Greeter.Register:output_type -> helloworld.v1.RegisterReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helloworld_v1_greeter_proto_init() }
func file_helloworld_v1_greeter_proto_init() {
	if File_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_helloworld_v1_greeter_proto = out.File
	file_helloworld_v1_greeter_proto_goTypes = nil
	file_helloworld_v1_greeter_proto_depIdxs = nil
}
