// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: api/helloworld/v1/driver.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 司机短信发送请求
type DriverSendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` //手机号码
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` //验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverSendSmsRequest) Reset() {
	*x = DriverSendSmsRequest{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverSendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverSendSmsRequest) ProtoMessage() {}

func (x *DriverSendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverSendSmsRequest.ProtoReflect.Descriptor instead.
func (*DriverSendSmsRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{0}
}

func (x *DriverSendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *DriverSendSmsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// 司机短信发送响应
type DriverSendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverSendSmsResponse) Reset() {
	*x = DriverSendSmsResponse{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverSendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverSendSmsResponse) ProtoMessage() {}

func (x *DriverSendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverSendSmsResponse.ProtoReflect.Descriptor instead.
func (*DriverSendSmsResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{1}
}

func (x *DriverSendSmsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverSendSmsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 司机登录注册一体化请求
type DriverLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` //手机号码
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` //验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLoginRequest) Reset() {
	*x = DriverLoginRequest{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLoginRequest) ProtoMessage() {}

func (x *DriverLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLoginRequest.ProtoReflect.Descriptor instead.
func (*DriverLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{2}
}

func (x *DriverLoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *DriverLoginRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// 司机登录注册一体化响应
type DriverLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverLoginResponse) Reset() {
	*x = DriverLoginResponse{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverLoginResponse) ProtoMessage() {}

func (x *DriverLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverLoginResponse.ProtoReflect.Descriptor instead.
func (*DriverLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{3}
}

func (x *DriverLoginResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 完善司机信息请求
type UpdateDriverRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                        //司机信息记录ID
	UserId            int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                  //用户ID
	DriverName        string                 `protobuf:"bytes,3,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`                       //司机姓名
	DriverLicense     string                 `protobuf:"bytes,4,opt,name=driver_license,json=driverLicense,proto3" json:"driver_license,omitempty"`              //驾驶证号
	VehicleLicense    string                 `protobuf:"bytes,5,opt,name=vehicle_license,json=vehicleLicense,proto3" json:"vehicle_license,omitempty"`           //行驶证号
	VehicleType       string                 `protobuf:"bytes,6,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`                    //车辆类型
	ApplicationStatus int64                  `protobuf:"varint,7,opt,name=application_status,json=applicationStatus,proto3" json:"application_status,omitempty"` //申请状态：1-待审核，2-审核通过，3-审核拒绝
	RejectReason      string                 `protobuf:"bytes,8,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`                 //拒绝原因
	AuditorId         int64                  `protobuf:"varint,9,opt,name=auditor_id,json=auditorId,proto3" json:"auditor_id,omitempty"`                         //审核人ID
	DriverId          int64                  `protobuf:"varint,10,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateDriverRequest) Reset() {
	*x = UpdateDriverRequest{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverRequest) ProtoMessage() {}

func (x *UpdateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDriverRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateDriverRequest) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *UpdateDriverRequest) GetDriverLicense() string {
	if x != nil {
		return x.DriverLicense
	}
	return ""
}

func (x *UpdateDriverRequest) GetVehicleLicense() string {
	if x != nil {
		return x.VehicleLicense
	}
	return ""
}

func (x *UpdateDriverRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *UpdateDriverRequest) GetApplicationStatus() int64 {
	if x != nil {
		return x.ApplicationStatus
	}
	return 0
}

func (x *UpdateDriverRequest) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *UpdateDriverRequest) GetAuditorId() int64 {
	if x != nil {
		return x.AuditorId
	}
	return 0
}

func (x *UpdateDriverRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

// 完善司机信息响应
type UpdateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResponse) Reset() {
	*x = UpdateDriverResponse{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResponse) ProtoMessage() {}

func (x *UpdateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDriverResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateDriverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 司机实名认证请求
type RealNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // 司机ID
	RealName      string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`  // 真实姓名
	IdCard        string                 `protobuf:"bytes,3,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`        // 身份证号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameRequest) Reset() {
	*x = RealNameRequest{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameRequest) ProtoMessage() {}

func (x *RealNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameRequest.ProtoReflect.Descriptor instead.
func (*RealNameRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{6}
}

func (x *RealNameRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *RealNameRequest) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *RealNameRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

// 司机实名认证响应
type RealNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealNameResponse) Reset() {
	*x = RealNameResponse{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealNameResponse) ProtoMessage() {}

func (x *RealNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealNameResponse.ProtoReflect.Descriptor instead.
func (*RealNameResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{7}
}

func (x *RealNameResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RealNameResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 首页统计数据请求
type HomeStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"` // 司机ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeStatRequest) Reset() {
	*x = HomeStatRequest{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeStatRequest) ProtoMessage() {}

func (x *HomeStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeStatRequest.ProtoReflect.Descriptor instead.
func (*HomeStatRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{8}
}

func (x *HomeStatRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

// 首页统计数据响应
type HomeStatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TodayIncome      float64                `protobuf:"fixed64,1,opt,name=today_income,json=todayIncome,proto3" json:"today_income,omitempty"`                 // 今日收益
	AvgIncome        float64                `protobuf:"fixed64,2,opt,name=avg_income,json=avgIncome,proto3" json:"avg_income,omitempty"`                       // 近7天平均收益
	RemainOrderCount int32                  `protobuf:"varint,3,opt,name=remain_order_count,json=remainOrderCount,proto3" json:"remain_order_count,omitempty"` // 剩余拒单次数
	WeekSuccessRate  float64                `protobuf:"fixed64,4,opt,name=week_success_rate,json=weekSuccessRate,proto3" json:"week_success_rate,omitempty"`   // 七日成单率（百分比，0~100）
	Code             int64                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`                                                   // 状态码
	Message          string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`                                              // 提示信息
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HomeStatResponse) Reset() {
	*x = HomeStatResponse{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeStatResponse) ProtoMessage() {}

func (x *HomeStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeStatResponse.ProtoReflect.Descriptor instead.
func (*HomeStatResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{9}
}

func (x *HomeStatResponse) GetTodayIncome() float64 {
	if x != nil {
		return x.TodayIncome
	}
	return 0
}

func (x *HomeStatResponse) GetAvgIncome() float64 {
	if x != nil {
		return x.AvgIncome
	}
	return 0
}

func (x *HomeStatResponse) GetRemainOrderCount() int32 {
	if x != nil {
		return x.RemainOrderCount
	}
	return 0
}

func (x *HomeStatResponse) GetWeekSuccessRate() float64 {
	if x != nil {
		return x.WeekSuccessRate
	}
	return 0
}

func (x *HomeStatResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HomeStatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 司机出车请求
type DriverDepartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`    // 司机ID
	VehicleId     int64                  `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"` // 车辆ID
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`                   // 纬度
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`                 // 经度
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`                             // 城市
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDepartRequest) Reset() {
	*x = DriverDepartRequest{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDepartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDepartRequest) ProtoMessage() {}

func (x *DriverDepartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDepartRequest.ProtoReflect.Descriptor instead.
func (*DriverDepartRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{10}
}

func (x *DriverDepartRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverDepartRequest) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *DriverDepartRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DriverDepartRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *DriverDepartRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

// 司机出车响应
type DriverDepartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDepartResponse) Reset() {
	*x = DriverDepartResponse{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDepartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDepartResponse) ProtoMessage() {}

func (x *DriverDepartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDepartResponse.ProtoReflect.Descriptor instead.
func (*DriverDepartResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{11}
}

func (x *DriverDepartResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverDepartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 司机接单请求
type DriverAcceptOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`                          // 订单ID
	DriverId        int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`                       // 司机ID
	DriverLatitude  float64                `protobuf:"fixed64,3,opt,name=driver_latitude,json=driverLatitude,proto3" json:"driver_latitude,omitempty"`    // 司机纬度
	DriverLongitude float64                `protobuf:"fixed64,4,opt,name=driver_longitude,json=driverLongitude,proto3" json:"driver_longitude,omitempty"` // 司机经度
	CarType         string                 `protobuf:"bytes,5,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`                           // 司机车型
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DriverAcceptOrderRequest) Reset() {
	*x = DriverAcceptOrderRequest{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverAcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverAcceptOrderRequest) ProtoMessage() {}

func (x *DriverAcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverAcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverAcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{12}
}

func (x *DriverAcceptOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DriverAcceptOrderRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverAcceptOrderRequest) GetDriverLatitude() float64 {
	if x != nil {
		return x.DriverLatitude
	}
	return 0
}

func (x *DriverAcceptOrderRequest) GetDriverLongitude() float64 {
	if x != nil {
		return x.DriverLongitude
	}
	return 0
}

func (x *DriverAcceptOrderRequest) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

// 司机接单响应
type DriverAcceptOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverAcceptOrderResponse) Reset() {
	*x = DriverAcceptOrderResponse{}
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverAcceptOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverAcceptOrderResponse) ProtoMessage() {}

func (x *DriverAcceptOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverAcceptOrderResponse.ProtoReflect.Descriptor instead.
func (*DriverAcceptOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_driver_proto_rawDescGZIP(), []int{13}
}

func (x *DriverAcceptOrderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverAcceptOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_driver_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_driver_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/helloworld/v1/driver.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\x14DriverSendSmsRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"E\n" +
	"\x15DriverSendSmsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x12DriverLoginRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"C\n" +
	"\x13DriverLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe2\x02\n" +
	"\x13UpdateDriverRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vdriver_name\x18\x03 \x01(\tR\n" +
	"driverName\x12%\n" +
	"\x0edriver_license\x18\x04 \x01(\tR\rdriverLicense\x12'\n" +
	"\x0fvehicle_license\x18\x05 \x01(\tR\x0evehicleLicense\x12!\n" +
	"\fvehicle_type\x18\x06 \x01(\tR\vvehicleType\x12-\n" +
	"\x12application_status\x18\a \x01(\x03R\x11applicationStatus\x12#\n" +
	"\rreject_reason\x18\b \x01(\tR\frejectReason\x12\x1d\n" +
	"\n" +
	"auditor_id\x18\t \x01(\x03R\tauditorId\x12\x1b\n" +
	"\tdriver_id\x18\n" +
	" \x01(\x03R\bdriverId\"D\n" +
	"\x14UpdateDriverResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"d\n" +
	"\x0fRealNameRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x17\n" +
	"\aid_card\x18\x03 \x01(\tR\x06idCard\"@\n" +
	"\x10RealNameResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\".\n" +
	"\x0fHomeStatRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\"\xdc\x01\n" +
	"\x10HomeStatResponse\x12!\n" +
	"\ftoday_income\x18\x01 \x01(\x01R\vtodayIncome\x12\x1d\n" +
	"\n" +
	"avg_income\x18\x02 \x01(\x01R\tavgIncome\x12,\n" +
	"\x12remain_order_count\x18\x03 \x01(\x05R\x10remainOrderCount\x12*\n" +
	"\x11week_success_rate\x18\x04 \x01(\x01R\x0fweekSuccessRate\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x9f\x01\n" +
	"\x13DriverDepartRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\x03R\tvehicleId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\"D\n" +
	"\x14DriverDepartResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc1\x01\n" +
	"\x18DriverAcceptOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12'\n" +
	"\x0fdriver_latitude\x18\x03 \x01(\x01R\x0edriverLatitude\x12)\n" +
	"\x10driver_longitude\x18\x04 \x01(\x01R\x0fdriverLongitude\x12\x19\n" +
	"\bcar_type\x18\x05 \x01(\tR\acarType\"I\n" +
	"\x19DriverAcceptOrderResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe1\x06\n" +
	"\x06Driver\x12{\n" +
	"\aSendSms\x12'.api.helloworld.v1.DriverSendSmsRequest\x1a(.api.helloworld.v1.DriverSendSmsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/driver/sendSms\x12s\n" +
	"\x05Login\x12%.api.helloworld.v1.DriverLoginRequest\x1a&.api.helloworld.v1.DriverLoginResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/driver/login\x12w\n" +
	"\x06Update\x12&.api.helloworld.v1.UpdateDriverRequest\x1a'.api.helloworld.v1.UpdateDriverResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/driver/update\x12s\n" +
	"\bRealName\x12\".api.helloworld.v1.RealNameRequest\x1a#.api.helloworld.v1.RealNameResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/driver/realName\x12p\n" +
	"\bHomeStat\x12\".api.helloworld.v1.HomeStatRequest\x1a#.api.helloworld.v1.HomeStatResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/driver/homeStat\x12w\n" +
	"\x06Depart\x12&.api.helloworld.v1.DriverDepartRequest\x1a'.api.helloworld.v1.DriverDepartResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/driver/depart\x12\x8b\x01\n" +
	"\vAcceptOrder\x12+.api.helloworld.v1.DriverAcceptOrderRequest\x1a,.api.helloworld.v1.DriverAcceptOrderResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/driver/acceptOrderB6\n" +
	"\x11api.helloworld.v1P\x01Z\x1fhelloworld/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_driver_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_driver_proto_rawDescData []byte
)

func file_api_helloworld_v1_driver_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_driver_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_driver_proto_rawDesc), len(file_api_helloworld_v1_driver_proto_rawDesc)))
	})
	return file_api_helloworld_v1_driver_proto_rawDescData
}

var file_api_helloworld_v1_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_helloworld_v1_driver_proto_goTypes = []any{
	(*DriverSendSmsRequest)(nil),      // 0: api.helloworld.v1.DriverSendSmsRequest
	(*DriverSendSmsResponse)(nil),     // 1: api.helloworld.v1.DriverSendSmsResponse
	(*DriverLoginRequest)(nil),        // 2: api.helloworld.v1.DriverLoginRequest
	(*DriverLoginResponse)(nil),       // 3: api.helloworld.v1.DriverLoginResponse
	(*UpdateDriverRequest)(nil),       // 4: api.helloworld.v1.UpdateDriverRequest
	(*UpdateDriverResponse)(nil),      // 5: api.helloworld.v1.UpdateDriverResponse
	(*RealNameRequest)(nil),           // 6: api.helloworld.v1.RealNameRequest
	(*RealNameResponse)(nil),          // 7: api.helloworld.v1.RealNameResponse
	(*HomeStatRequest)(nil),           // 8: api.helloworld.v1.HomeStatRequest
	(*HomeStatResponse)(nil),          // 9: api.helloworld.v1.HomeStatResponse
	(*DriverDepartRequest)(nil),       // 10: api.helloworld.v1.DriverDepartRequest
	(*DriverDepartResponse)(nil),      // 11: api.helloworld.v1.DriverDepartResponse
	(*DriverAcceptOrderRequest)(nil),  // 12: api.helloworld.v1.DriverAcceptOrderRequest
	(*DriverAcceptOrderResponse)(nil), // 13: api.helloworld.v1.DriverAcceptOrderResponse
}
var file_api_helloworld_v1_driver_proto_depIdxs = []int32{
	0,  // 0: api.helloworld.v1.Driver.SendSms:input_type -> api.helloworld.v1.DriverSendSmsRequest
	2,  // 1: api.helloworld.v1.Driver.Login:input_type -> api.helloworld.v1.DriverLoginRequest
	4,  // 2: api.helloworld.v1.Driver.Update:input_type -> api.helloworld.v1.UpdateDriverRequest
	6,  // 3: api.helloworld.v1.Driver.RealName:input_type -> api.helloworld.v1.RealNameRequest
	8,  // 4: api.helloworld.v1.Driver.HomeStat:input_type -> api.helloworld.v1.HomeStatRequest
	10, // 5: api.helloworld.v1.Driver.Depart:input_type -> api.helloworld.v1.DriverDepartRequest
	12, // 6: api.helloworld.v1.Driver.AcceptOrder:input_type -> api.helloworld.v1.DriverAcceptOrderRequest
	1,  // 7: api.helloworld.v1.Driver.SendSms:output_type -> api.helloworld.v1.DriverSendSmsResponse
	3,  // 8: api.helloworld.v1.Driver.Login:output_type -> api.helloworld.v1.DriverLoginResponse
	5,  // 9: api.helloworld.v1.Driver.Update:output_type -> api.helloworld.v1.UpdateDriverResponse
	7,  // 10: api.helloworld.v1.Driver.RealName:output_type -> api.helloworld.v1.RealNameResponse
	9,  // 11: api.helloworld.v1.Driver.HomeStat:output_type -> api.helloworld.v1.HomeStatResponse
	11, // 12: api.helloworld.v1.Driver.Depart:output_type -> api.helloworld.v1.DriverDepartResponse
	13, // 13: api.helloworld.v1.Driver.AcceptOrder:output_type -> api.helloworld.v1.DriverAcceptOrderResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_driver_proto_init() }
func file_api_helloworld_v1_driver_proto_init() {
	if File_api_helloworld_v1_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_driver_proto_rawDesc), len(file_api_helloworld_v1_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_driver_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_driver_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_driver_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_driver_proto = out.File
	file_api_helloworld_v1_driver_proto_goTypes = nil
	file_api_helloworld_v1_driver_proto_depIdxs = nil
}
