// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: api/helloworld/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 短信验证请求
type UserSendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` //手机号码
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` //验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSendSmsRequest) Reset() {
	*x = UserSendSmsRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSendSmsRequest) ProtoMessage() {}

func (x *UserSendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSendSmsRequest.ProtoReflect.Descriptor instead.
func (*UserSendSmsRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserSendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserSendSmsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// 短信验证响应
type UserSendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSendSmsResponse) Reset() {
	*x = UserSendSmsResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSendSmsResponse) ProtoMessage() {}

func (x *UserSendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSendSmsResponse.ProtoReflect.Descriptor instead.
func (*UserSendSmsResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserSendSmsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserSendSmsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 登录注册一体化请求
type UserLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"` //手机号码
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` //验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginRequest) Reset() {
	*x = UserLoginRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginRequest) ProtoMessage() {}

func (x *UserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginRequest.ProtoReflect.Descriptor instead.
func (*UserLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserLoginRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// 登录注册一体化响应
type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserLoginResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 完善用户信息请求
type UserUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                            //用户ID
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`                     //手机号码
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` //用户名
	NickName      string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` //昵称
	IdCard        string                 `protobuf:"bytes,5,opt,name=id_card,json=idCard,proto3" json:"id_card,omitempty"`       //身份证号
	Sex           string                 `protobuf:"bytes,6,opt,name=sex,proto3" json:"sex,omitempty"`                           //性别
	Mileage       string                 `protobuf:"bytes,7,opt,name=mileage,proto3" json:"mileage,omitempty"`                   //里程数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateRequest) Reset() {
	*x = UserUpdateRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateRequest) ProtoMessage() {}

func (x *UserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserUpdateRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserUpdateRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserUpdateRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserUpdateRequest) GetIdCard() string {
	if x != nil {
		return x.IdCard
	}
	return ""
}

func (x *UserUpdateRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *UserUpdateRequest) GetMileage() string {
	if x != nil {
		return x.Mileage
	}
	return ""
}

// 完善用户信息响应
type UserUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateResponse) Reset() {
	*x = UserUpdateResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateResponse) ProtoMessage() {}

func (x *UserUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateResponse.ProtoReflect.Descriptor instead.
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserUpdateResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 搜索历史请求
type UserSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`            //用户ID
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`                         //搜索关键词
	SearchTime    string                 `protobuf:"bytes,3,opt,name=search_time,json=searchTime,proto3" json:"search_time,omitempty"` //搜索时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSearchRequest) Reset() {
	*x = UserSearchRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchRequest) ProtoMessage() {}

func (x *UserSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchRequest.ProtoReflect.Descriptor instead.
func (*UserSearchRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserSearchRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *UserSearchRequest) GetSearchTime() string {
	if x != nil {
		return x.SearchTime
	}
	return ""
}

// 搜索历史响应
type UserSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSearchResponse) Reset() {
	*x = UserSearchResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSearchResponse) ProtoMessage() {}

func (x *UserSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSearchResponse.ProtoReflect.Descriptor instead.
func (*UserSearchResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserSearchResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserSearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 用户叫车请求
type CreateUserOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   int64                  `protobuf:"varint,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"` //乘客ID
	OrderCode     string                 `protobuf:"bytes,2,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`        //订单编号
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`                             //订单金额
	OrderStatus   string                 `protobuf:"bytes,4,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`  //订单状态
	StartAddr     string                 `protobuf:"bytes,5,opt,name=start_addr,json=startAddr,proto3" json:"start_addr,omitempty"`        //起始地址
	EndEnd        string                 `protobuf:"bytes,6,opt,name=end_end,json=endEnd,proto3" json:"end_end,omitempty"`                 //目的地地址
	Driver        int64                  `protobuf:"varint,7,opt,name=driver,proto3" json:"driver,omitempty"`                              //司机ID
	StartTime     string                 `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`        //开始时间
	EndTime       string                 `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`              //结束时间
	PayStatus     string                 `protobuf:"bytes,10,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`       //支付状态
	PayType       string                 `protobuf:"bytes,11,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`             //支付方式
	OrderType     string                 `protobuf:"bytes,12,opt,name=order_type,json=orderType,proto3" json:"order_type,omitempty"`       //订单类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserOrderRequest) Reset() {
	*x = CreateUserOrderRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserOrderRequest) ProtoMessage() {}

func (x *CreateUserOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateUserOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *CreateUserOrderRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *CreateUserOrderRequest) GetOrderCode() string {
	if x != nil {
		return x.OrderCode
	}
	return ""
}

func (x *CreateUserOrderRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateUserOrderRequest) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *CreateUserOrderRequest) GetStartAddr() string {
	if x != nil {
		return x.StartAddr
	}
	return ""
}

func (x *CreateUserOrderRequest) GetEndEnd() string {
	if x != nil {
		return x.EndEnd
	}
	return ""
}

func (x *CreateUserOrderRequest) GetDriver() int64 {
	if x != nil {
		return x.Driver
	}
	return 0
}

func (x *CreateUserOrderRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateUserOrderRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateUserOrderRequest) GetPayStatus() string {
	if x != nil {
		return x.PayStatus
	}
	return ""
}

func (x *CreateUserOrderRequest) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *CreateUserOrderRequest) GetOrderType() string {
	if x != nil {
		return x.OrderType
	}
	return ""
}

// 用户叫车响应
type CreateUserOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserOrderResponse) Reset() {
	*x = CreateUserOrderResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserOrderResponse) ProtoMessage() {}

func (x *CreateUserOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateUserOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserOrderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateUserOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 评价司机请求
type UserCommentDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassengerId   int64                  `protobuf:"varint,1,opt,name=passenger_id,json=passengerId,proto3" json:"passenger_id,omitempty"` //乘客ID
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`             //订单ID
	DriverId      int64                  `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`          //司机ID
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                                //评分（1-5分）
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                             //评价内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCommentDriverRequest) Reset() {
	*x = UserCommentDriverRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCommentDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommentDriverRequest) ProtoMessage() {}

func (x *UserCommentDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommentDriverRequest.ProtoReflect.Descriptor instead.
func (*UserCommentDriverRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserCommentDriverRequest) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *UserCommentDriverRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UserCommentDriverRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UserCommentDriverRequest) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *UserCommentDriverRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 评价司机响应
type UserCommentDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      //响应状态码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCommentDriverResponse) Reset() {
	*x = UserCommentDriverResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCommentDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommentDriverResponse) ProtoMessage() {}

func (x *UserCommentDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommentDriverResponse.ProtoReflect.Descriptor instead.
func (*UserCommentDriverResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *UserCommentDriverResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserCommentDriverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 创建行程请求
type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      //用户ID
	StartLocation string                 `protobuf:"bytes,2,opt,name=start_location,json=startLocation,proto3" json:"start_location,omitempty"` //起点
	EndLocation   string                 `protobuf:"bytes,3,opt,name=end_location,json=endLocation,proto3" json:"end_location,omitempty"`       //终点
	CarType       string                 `protobuf:"bytes,4,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`                   //车型（如 economy, comfort, luxury）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTripRequest) GetStartLocation() string {
	if x != nil {
		return x.StartLocation
	}
	return ""
}

func (x *CreateTripRequest) GetEndLocation() string {
	if x != nil {
		return x.EndLocation
	}
	return ""
}

func (x *CreateTripRequest) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

// 创建行程响应
type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`    //行程ID
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`                  //预估费用
	CarType       string                 `protobuf:"bytes,3,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"` //车型
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                //结果描述
	Code          int64                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`                     //响应状态码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CreateTripResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTripResponse) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *CreateTripResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTripResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 获取当前位置请求
type GetCurrentLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    //用户ID
	BaiduAk       string                 `protobuf:"bytes,2,opt,name=baidu_ak,json=baiduAk,proto3" json:"baidu_ak,omitempty"` //百度地图API密钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLocationRequest) Reset() {
	*x = GetCurrentLocationRequest{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLocationRequest) ProtoMessage() {}

func (x *GetCurrentLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLocationRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentLocationRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetCurrentLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCurrentLocationRequest) GetBaiduAk() string {
	if x != nil {
		return x.BaiduAk
	}
	return ""
}

// 获取当前位置响应
type GetCurrentLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`   //纬度
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"` //经度
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`       //详细地址
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`             //城市
	Province      string                 `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`     //省份
	District      string                 `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`     //区县
	Code          int64                  `protobuf:"varint,7,opt,name=code,proto3" json:"code,omitempty"`            //响应状态码
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`       //响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLocationResponse) Reset() {
	*x = GetCurrentLocationResponse{}
	mi := &file_api_helloworld_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLocationResponse) ProtoMessage() {}

func (x *GetCurrentLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLocationResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentLocationResponse) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetCurrentLocationResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetCurrentLocationResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetCurrentLocationResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetCurrentLocationResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetCurrentLocationResponse) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *GetCurrentLocationResponse) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *GetCurrentLocationResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCurrentLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_helloworld_v1_user_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1capi/helloworld/v1/user.proto\x12\x11api.helloworld.v1\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\x12UserSendSmsRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"C\n" +
	"\x13UserSendSmsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x10UserLoginRequest\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"A\n" +
	"\x11UserLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xba\x01\n" +
	"\x11UserUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x17\n" +
	"\aid_card\x18\x05 \x01(\tR\x06idCard\x12\x10\n" +
	"\x03sex\x18\x06 \x01(\tR\x03sex\x12\x18\n" +
	"\amileage\x18\a \x01(\tR\amileage\"B\n" +
	"\x12UserUpdateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x11UserSearchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1f\n" +
	"\vsearch_time\x18\x03 \x01(\tR\n" +
	"searchTime\"B\n" +
	"\x12UserSearchResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf8\x02\n" +
	"\x16CreateUserOrderRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\x03R\vpassengerId\x12\x1d\n" +
	"\n" +
	"order_code\x18\x02 \x01(\tR\torderCode\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12!\n" +
	"\forder_status\x18\x04 \x01(\tR\vorderStatus\x12\x1d\n" +
	"\n" +
	"start_addr\x18\x05 \x01(\tR\tstartAddr\x12\x17\n" +
	"\aend_end\x18\x06 \x01(\tR\x06endEnd\x12\x16\n" +
	"\x06driver\x18\a \x01(\x03R\x06driver\x12\x1d\n" +
	"\n" +
	"start_time\x18\b \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\t \x01(\tR\aendTime\x12\x1d\n" +
	"\n" +
	"pay_status\x18\n" +
	" \x01(\tR\tpayStatus\x12\x19\n" +
	"\bpay_type\x18\v \x01(\tR\apayType\x12\x1d\n" +
	"\n" +
	"order_type\x18\f \x01(\tR\torderType\"G\n" +
	"\x17CreateUserOrderResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa5\x01\n" +
	"\x18UserCommentDriverRequest\x12!\n" +
	"\fpassenger_id\x18\x01 \x01(\x03R\vpassengerId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\x03R\bdriverId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"I\n" +
	"\x19UserCommentDriverResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x91\x01\n" +
	"\x11CreateTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0estart_location\x18\x02 \x01(\tR\rstartLocation\x12!\n" +
	"\fend_location\x18\x03 \x01(\tR\vendLocation\x12\x19\n" +
	"\bcar_type\x18\x04 \x01(\tR\acarType\"\x8c\x01\n" +
	"\x12CreateTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x19\n" +
	"\bcar_type\x18\x03 \x01(\tR\acarType\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x03R\x04code\"O\n" +
	"\x19GetCurrentLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bbaidu_ak\x18\x02 \x01(\tR\abaiduAk\"\xea\x01\n" +
	"\x1aGetCurrentLocationResponse\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x1a\n" +
	"\bdistrict\x18\x06 \x01(\tR\bdistrict\x12\x12\n" +
	"\x04code\x18\a \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage2\xfa\a\n" +
	"\x04User\x12u\n" +
	"\aSendSms\x12%.api.helloworld.v1.UserSendSmsRequest\x1a&.api.helloworld.v1.UserSendSmsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/user/sendSms\x12m\n" +
	"\x05Login\x12#.api.helloworld.v1.UserLoginRequest\x1a$.api.helloworld.v1.UserLoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/user/login\x12q\n" +
	"\x06Update\x12$.api.helloworld.v1.UserUpdateRequest\x1a%.api.helloworld.v1.UserUpdateResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/update\x12y\n" +
	"\n" +
	"UserSearch\x12$.api.helloworld.v1.UserSearchRequest\x1a%.api.helloworld.v1.UserSearchResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/user/userSearch\x12\x88\x01\n" +
	"\x0fCreateUserOrder\x12).api.helloworld.v1.CreateUserOrderRequest\x1a*.api.helloworld.v1.CreateUserOrderResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/order/userOrder\x12\x87\x01\n" +
	"\rCommentDriver\x12+.api.helloworld.v1.UserCommentDriverRequest\x1a,.api.helloworld.v1.UserCommentDriverResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/user/comment\x12s\n" +
	"\n" +
	"CreateTrip\x12$.api.helloworld.v1.CreateTripRequest\x1a%.api.helloworld.v1.CreateTripResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/user/trip\x12\x93\x01\n" +
	"\x12GetCurrentLocation\x12,.api.helloworld.v1.GetCurrentLocationRequest\x1a-.api.helloworld.v1.GetCurrentLocationResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/user/currentLocationB6\n" +
	"\x11api.helloworld.v1P\x01Z\x1fhelloworld/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_user_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_user_proto_rawDescData []byte
)

func file_api_helloworld_v1_user_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_user_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_user_proto_rawDesc), len(file_api_helloworld_v1_user_proto_rawDesc)))
	})
	return file_api_helloworld_v1_user_proto_rawDescData
}

var file_api_helloworld_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_helloworld_v1_user_proto_goTypes = []any{
	(*UserSendSmsRequest)(nil),         // 0: api.helloworld.v1.UserSendSmsRequest
	(*UserSendSmsResponse)(nil),        // 1: api.helloworld.v1.UserSendSmsResponse
	(*UserLoginRequest)(nil),           // 2: api.helloworld.v1.UserLoginRequest
	(*UserLoginResponse)(nil),          // 3: api.helloworld.v1.UserLoginResponse
	(*UserUpdateRequest)(nil),          // 4: api.helloworld.v1.UserUpdateRequest
	(*UserUpdateResponse)(nil),         // 5: api.helloworld.v1.UserUpdateResponse
	(*UserSearchRequest)(nil),          // 6: api.helloworld.v1.UserSearchRequest
	(*UserSearchResponse)(nil),         // 7: api.helloworld.v1.UserSearchResponse
	(*CreateUserOrderRequest)(nil),     // 8: api.helloworld.v1.CreateUserOrderRequest
	(*CreateUserOrderResponse)(nil),    // 9: api.helloworld.v1.CreateUserOrderResponse
	(*UserCommentDriverRequest)(nil),   // 10: api.helloworld.v1.UserCommentDriverRequest
	(*UserCommentDriverResponse)(nil),  // 11: api.helloworld.v1.UserCommentDriverResponse
	(*CreateTripRequest)(nil),          // 12: api.helloworld.v1.CreateTripRequest
	(*CreateTripResponse)(nil),         // 13: api.helloworld.v1.CreateTripResponse
	(*GetCurrentLocationRequest)(nil),  // 14: api.helloworld.v1.GetCurrentLocationRequest
	(*GetCurrentLocationResponse)(nil), // 15: api.helloworld.v1.GetCurrentLocationResponse
}
var file_api_helloworld_v1_user_proto_depIdxs = []int32{
	0,  // 0: api.helloworld.v1.User.SendSms:input_type -> api.helloworld.v1.UserSendSmsRequest
	2,  // 1: api.helloworld.v1.User.Login:input_type -> api.helloworld.v1.UserLoginRequest
	4,  // 2: api.helloworld.v1.User.Update:input_type -> api.helloworld.v1.UserUpdateRequest
	6,  // 3: api.helloworld.v1.User.UserSearch:input_type -> api.helloworld.v1.UserSearchRequest
	8,  // 4: api.helloworld.v1.User.CreateUserOrder:input_type -> api.helloworld.v1.CreateUserOrderRequest
	10, // 5: api.helloworld.v1.User.CommentDriver:input_type -> api.helloworld.v1.UserCommentDriverRequest
	12, // 6: api.helloworld.v1.User.CreateTrip:input_type -> api.helloworld.v1.CreateTripRequest
	14, // 7: api.helloworld.v1.User.GetCurrentLocation:input_type -> api.helloworld.v1.GetCurrentLocationRequest
	1,  // 8: api.helloworld.v1.User.SendSms:output_type -> api.helloworld.v1.UserSendSmsResponse
	3,  // 9: api.helloworld.v1.User.Login:output_type -> api.helloworld.v1.UserLoginResponse
	5,  // 10: api.helloworld.v1.User.Update:output_type -> api.helloworld.v1.UserUpdateResponse
	7,  // 11: api.helloworld.v1.User.UserSearch:output_type -> api.helloworld.v1.UserSearchResponse
	9,  // 12: api.helloworld.v1.User.CreateUserOrder:output_type -> api.helloworld.v1.CreateUserOrderResponse
	11, // 13: api.helloworld.v1.User.CommentDriver:output_type -> api.helloworld.v1.UserCommentDriverResponse
	13, // 14: api.helloworld.v1.User.CreateTrip:output_type -> api.helloworld.v1.CreateTripResponse
	15, // 15: api.helloworld.v1.User.GetCurrentLocation:output_type -> api.helloworld.v1.GetCurrentLocationResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_user_proto_init() }
func file_api_helloworld_v1_user_proto_init() {
	if File_api_helloworld_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_user_proto_rawDesc), len(file_api_helloworld_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_user_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_user_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_user_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_user_proto = out.File
	file_api_helloworld_v1_user_proto_goTypes = nil
	file_api_helloworld_v1_user_proto_depIdxs = nil
}
